name: Continuous Integration

on:
  push:
    branches:
      - main

    workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build application
      - run: npm run build
      - run: pm2 stop main
      - run: pm2 start main
