name: Continuous Integration

on:
  push:
    branches:
      - main

    workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Stop PM2
        run: pm2 stop main

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start PM2
        run: pm2 start /root/actions-runner/_work/front-end-battle-back/front-end-battle-back/dist/main.js