name: Continuous Integration

on:
  push:
    branches:
      - main

    workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    env:
          DB_USER: ${{ dev.DB_USER }}
          DB_PASSWORD: ${{ dev.DB_PASSWORD }}
          PORT: ${{ dev.PORT }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Restart server application
        run: pm2 restart feb